import {test} from 'node:test';import assert from 'node:assert/strict';
import {Extractor} from '../dist/extraction.js';import {configFromEnv} from '../dist/config.js';import {extractionSchema} from '../dist/types.js';
import {replacementBindingProblems,applyRepair} from '../dist/repair.js';
const req={user_id:'u',request_id:'replacement-feedback',session_id:'s',messages:[{role:'user',content:'I now use Safari as my default browser on my work laptop.',timestamp:'2026-02-01T00:00:00Z'}]};
const target={id:'actual-browser-id',content:'User uses Firefox on their work laptop.',subject:'user',predicate:'default_browser',scope:'work laptop',value:'Firefox',state:'active',modality:'confirmed',kind:'fact',cardinality:'single',time_text:'',valid_from:null,valid_to:null,supersedes:[],depends_on:[],source_ids:['old'],source_quotes:['I use Firefox on my work laptop.'],created_at:'2026-01-01T00:00:00Z',observed_at:'2026-01-01T00:00:00Z',vector:null,entities:[],revision:1};
test('actual replacement repair receives the mismatched fields and model-visible target handle before re-verification',async()=>{
 let feedback='',verified:any,calls=0;
 const p=await new Extractor(configFromEnv({MEMORY_MODE:'enhanced'}),{json:async(_system:string,input:string,_s:any,ctx:any)=>{const x=JSON.parse(input);calls++;if(ctx.purpose==='extraction')return {facts:[{content:req.messages[0].content,subject:'user',predicate:'preferred_browser',scope:'work laptop',value:'Safari',cardinality:'single',supersedes:['m0'],sources:[{index:0,quote:req.messages[0].content}]}],operations:[]};feedback=x.REPAIR_FEEDBACK;return {fact_edits:[{index:0,changes:{predicate:'default_browser'}}]};},verify:async(p:any)=>{verified=structuredClone(p);return [];},embedBatch:async(xs:string[])=>xs.map(()=>[1,0])} as any).prepare(req,{revision:1,facts:[target],tail:[],anchor:null} as any,AbortSignal.timeout(3000));
 assert.deepEqual(p.degraded,[]);assert.equal(calls,2);assert.equal(verified.facts[0].predicate,'default_browser');assert.deepEqual(verified.facts[0].supersedes,[target.id]);
 const json=feedback.slice(feedback.indexOf('{'),feedback.indexOf('. Reuse matching'));
 const details=JSON.parse(json).replacement_details;assert.ok(details,'feedback must show the specific old target and mismatch');assert.equal(details[0].fact,0);assert.equal(details[0].proposed.predicate,'preferred_browser');assert.equal(details[0].selected_targets[0].id,'m0');assert.equal(details[0].selected_targets[0].predicate,'default_browser');assert.deepEqual(details[0].selected_targets[0].mismatched_fields,['property']);assert.doesNotMatch(JSON.stringify(details),/actual-browser-id/);
});
test('replacement explanations distinguish property and scope, preserving valid references and all source text',()=>{
 const base={content:'Priya named her daughter Violet.',subject:"Priya's daughter",predicate:'first_name',scope:'friend Priya',value:'Violet',sources:[{index:0,quote:'Priya named her daughter Violet.'}],supersedes:['full','name','other']};
 const p=extractionSchema.parse({facts:[base],operations:[]}),before=structuredClone(p),targets=[{id:'full',content:'Her full name is Violet Mae.',subject:base.subject,predicate:'full_name',scope:''},{id:'name',content:'Her first name is Rose.',subject:base.subject,predicate:'first name',scope:'friend_Priya'},{id:'other',content:'Another child is named Rose.',subject:"Diane's daughter",predicate:'first_name',scope:'friend Priya'}];
 const problems=replacementBindingProblems(p,targets,id=>({full:'m0',name:'m1',other:'new:0'}[id]!));assert.deepEqual(problems[0].selected_targets.map(t=>[t.id,t.mismatched_fields]),[['m0',['property','scope']],['new:0',['subject']]]);assert.deepEqual(p,before);
 const sourceOnly=applyRepair(p,{fact_edits:[{index:0,changes:{sources:[{index:0,quote:'Violet'}]}}]},{fact_indices:[0],operation_indices:[],source_indices:[0]});assert.equal(replacementBindingProblems(sourceOnly,targets).length,1);
 const corrected=applyRepair(p,{fact_edits:[{index:0,changes:{supersedes:['name']}}]},{fact_indices:[0],operation_indices:[],source_indices:[0]});assert.deepEqual(replacementBindingProblems(corrected,targets),[]);assert.equal(corrected.facts[0].predicate,'first_name');assert.equal(corrected.facts[0].scope,'friend Priya');assert.equal(corrected.facts[0].sources[0].quote,base.sources[0].quote);
});
