import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {sourceOperationWork,decodeSourceOperations} from '../dist/source-operations.js';
import {sourceOperationNeedsBatches,sourceOperationWholeInput,sourceOperationBatches,sourceScreenInput,decodeSourceScreen,sourceAnchorInput,sourceClosureInput,decodeSourceClosure,validateSourceBatchPlan,prepareSourceBatches} from '../dist/source-operation-batches.js';
import {Extractor,hash} from '../dist/extraction.js';import {TenantStore} from '../dist/storage.js';import {configFromEnv} from '../dist/config.js';
const timestamp='2026-01-01T00:00:00Z',primary='Your gym is Peak Gym.',echo='Peak Gym was my incorrect claim.',command="Please don't store that.";
const req={user_id:'u',request_id:'reject',session_id:'s',messages:[{role:'user',content:'That earlier gym claim was wrong. '+command,timestamp}]};
const contents=Array.from({length:160},(_,i)=>'Background astronomy topic '+i+'. '+'Galaxies are observable in the sky. '.repeat(55));contents[0]='I use Firefox.';contents[1]=primary+' Water is available.';contents[70]='My brother goes to Peak Gym.';contents[130]=echo+' Bring water.';
const history=contents.map((content,i)=>({id:hash(`u\0seed\0${i}`),session_id:'s',ordinal:i,searchable:true,role:i===0||i===70?'user':'assistant',content,timestamp}));const work=()=>sourceOperationWork(req,[],history);
function response(purpose:string,input:any):any{
 if(purpose==='source_operation_screen')return {rows:input.UNITS.map((u:any)=>[u.unit,u.text.includes(primary)?'candidate':u.text.includes('My brother')?'context':'irrelevant'])};
 if(purpose==='source_operation'){const target=input.SOURCES.find((s:any)=>s.content.includes(primary));return {decisions:[{instruction:0,action:'reject_source',target_slots:[target.slot],cuts:[{message:target.slot,quote:primary},{message:0,quote:command}]}]};}
 if(purpose==='source_operation_closure')return {rows:input.RESOLVED_TARGETS.flatMap((t:any)=>input.UNITS.map((u:any)=>{const quotes=[primary,echo,command].filter(q=>u.text.includes(q));return [t.instruction,u.unit,quotes.length?'cut':'retain',quotes];}))};throw Error(purpose);
}
const call=async(_p:string,input:string,_s:AbortSignal,purpose:string)=>response(purpose,JSON.parse(input));
test('complete batches preserve every original UTF-16 source within model input limits',()=>{
 const w=work();assert.ok(sourceOperationNeedsBatches(w));assert.throws(()=>sourceOperationWholeInput(w),/capacity/);const p=sourceOperationBatches(w);assert.ok(p.batches.length>1);assert.deepEqual(p.batches.flatMap(b=>b.units.map(u=>u.unit)),p.units.map(u=>u.unit));
 for(const source of w.sources)assert.equal(p.units.filter(u=>u.slot===source.slot).map(u=>u.text).join(''),source.content);
 for(const b of p.batches){assert.ok(JSON.stringify(sourceScreenInput(w,b)).length<=180000);assert.ok(b.units.length<=64);assert.ok(b.units.reduce((n,u)=>n+u.text.length,0)<=64000);}
 const unicode=sourceOperationWork(req,[],[{...history[1],content:'x'.repeat(15999)+'😀'+'中文'.repeat(18000)}]);for(const u of sourceOperationBatches(unicode).units)assert.doesNotMatch(u.text,/^[\uDC00-\uDFFF]|[\uD800-\uDBFF]$/u);
 const small=sourceOperationWork(req,[],history.slice(0,2));assert.equal(sourceOperationNeedsBatches(small),false);assert.ok(sourceOperationWholeInput(small).TARGETS.every(t=>!('text' in t)));
});
test('closure catches an echo screened irrelevant and binds every final cut to complete review',async()=>{
 const w=work(),plan=await prepareSourceBatches(w,AbortSignal.timeout(3000),call as any);validateSourceBatchPlan(plan,w);const slot=w.sources.find(s=>s.content.includes(echo))!.slot;assert.ok(plan.decisions[0].cuts.some(c=>c.message===slot&&c.quote===echo));assert.ok(plan.batch_review!.screenings.flat().some(([u,r])=>sourceOperationBatches(w).units[u].slot===slot&&r==='irrelevant'));
 const changed=structuredClone(plan);changed.decisions[0].cuts.pop();assert.throws(()=>validateSourceBatchPlan(changed,w),/changed after/);const missing=structuredClone(plan);missing.batch_review!.closures.pop();assert.throws(()=>validateSourceBatchPlan(missing,w),/incomplete/);const forged=structuredClone(plan);forged.batch_review!.fingerprint='wrong';assert.throws(()=>validateSourceBatchPlan(forged,w),/identity/);
});
test('missing screening, foreign global targets, closure omissions and ownership vetoes reject',async()=>{
 const w=work(),p=sourceOperationBatches(w),screens=p.batches.map(b=>decodeSourceScreen(response('source_operation_screen',sourceScreenInput(w,b)),b));assert.throws(()=>decodeSourceScreen({rows:[]},p.batches[0]),/omitted/);
 const anchor=decodeSourceOperations(response('source_operation',sourceAnchorInput(w,p,screens).input),w),batch=p.batches[0],raw=response('source_operation_closure',sourceClosureInput(w,batch,anchor));assert.throws(()=>decodeSourceClosure({rows:raw.rows.slice(1)},batch,anchor),/cover/);
 for(const effect of ['uncertain','adopted']){const bad=structuredClone(raw);bad.rows[0][2]=effect;bad.rows[0][3]=[];assert.throws(()=>decodeSourceClosure(bad,batch,anchor),/unresolved ownership or human adoption/);}const extra=structuredClone(raw);extra.rows.push([0,99999,'retain',[]]);assert.throws(()=>decodeSourceClosure(extra,batch,anchor),/Unknown/);
 const selected=sourceAnchorInput(w,p,screens).selected,foreign=w.targets.find(t=>!selected.has(t.slot))!;await assert.rejects(()=>prepareSourceBatches(w,AbortSignal.timeout(3000),async(prompt,input,signal,purpose)=>purpose==='source_operation'?{decisions:[{instruction:0,action:'reject_source',target_slots:[foreign.slot],cuts:[{message:foreign.slot,quote:foreign.text},{message:0,quote:command}]}]}:call(prompt,input,signal,purpose)),/not in adjudicated context/);
});
test('closure cannot retain an authorized target then report success',async()=>{
 await assert.rejects(()=>prepareSourceBatches(work(),AbortSignal.timeout(3000),async(p,i,s,purpose)=>{const out=await call(p,i,s,purpose);if(purpose==='source_operation_closure')for(const row of out.rows)if(row[3].includes(primary)){row[2]='retain';row[3]=[];}return out;}),/left an authorized target/);
});
test('bounded worker phases order global resolution before closure and drain cancelled siblings',async()=>{
 const w=work(),p=sourceOperationBatches(w);let active=0,peak=0,screened=0,anchored=false;
 await prepareSourceBatches(w,AbortSignal.timeout(3000),async(prompt,input,signal,purpose)=>{active++;peak=Math.max(peak,active);if(purpose==='source_operation')assert.equal(screened,p.batches.length);if(purpose==='source_operation_closure')assert.ok(anchored);try{await new Promise(r=>setTimeout(r,2));if(purpose==='source_operation_screen')screened++;if(purpose==='source_operation')anchored=true;return await call(prompt,input,signal,purpose);}finally{active--;}});assert.ok(peak<=3&&peak>1);assert.equal(active,0);
 let calls=0,aborted=0;await assert.rejects(()=>prepareSourceBatches(w,AbortSignal.timeout(3000),async(_p,_i,s,purpose)=>{assert.equal(purpose,'source_operation_screen');const n=++calls;if(n===1)return {rows:[]};return await new Promise((_resolve,reject)=>{const stop=()=>{aborted++;reject(Error('cancelled sibling'));};if(s.aborted)stop();else s.addEventListener('abort',stop,{once:true});});}));assert.ok(calls<=3);assert.equal(aborted,calls-1);
});
test('ordinary global decisions have no closure or source deletion authority',async()=>{
 const w=work(),p=await prepareSourceBatches(w,AbortSignal.timeout(3000),async(prompt,input,signal,purpose)=>{assert.notEqual(purpose,'source_operation_closure');return purpose==='source_operation'?{decisions:[{instruction:0,action:'ordinary',target_slots:[],cuts:[]}]}:call(prompt,input,signal,purpose);});assert.equal(p.batch_review!.closures.length,0);assert.deepEqual(p.decisions[0].cuts,[]);validateSourceBatchPlan(p,w);
});
test('v8 validates full-history proof at atomic commit, preserving state on tamper and rollback',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'source-batches-')),store=new TenantStore(dir,'u'),config=configFromEnv({MEMORY_MODE:'enhanced',MEMORY_ERASURE_BINDING:'true',MEMORY_SOURCE_ERASURE:'true',MEMORY_SEMANTIC_TRANSITIONS:'true',MEMORY_SOURCE_OPERATIONS:'true',MEMORY_SOURCE_OPERATION_HISTORY:'true',MEMORY_SOURCE_OPERATION_BATCHES:'true'});
 const models={json:async(p:string,i:string,s:AbortSignal,c:any)=>{if(c.purpose.startsWith('source_operation'))return call(p,i,s,c.purpose);if(c.purpose==='extraction'){const d=JSON.parse(i);return {facts:d.NEW_MESSAGES.length>1?[{content:'I use Firefox.',subject:'user',predicate:'browser',value:'Firefox',sources:[{index:0,quote:'I use Firefox.'}]}]:[],operations:[]};}throw Error(c.purpose);},verify:async()=>[],embedBatch:async(xs:string[])=>xs.map(()=>[1,0])};const x=new Extractor(config,models as any);
 try{const seed={...req,request_id:'seed',messages:history.map(({role,content,timestamp})=>({role,content,timestamp}))};const a=await x.prepare(seed,store.snapshot('s'),AbortSignal.timeout(3000));store.commit(seed,hash(JSON.stringify(seed)),a,0);assert.equal(store.meta('source_format'),'dual-source-v8');const before=store.snapshot('s'),b=await x.prepare(req,before,AbortSignal.timeout(3000));assert.ok(b.sourceOperationPlan?.batch_review);
 const corrupt=structuredClone(b);corrupt.sourceOperationPlan!.batch_review!.screenings=[];assert.throws(()=>store.commit(req,hash(JSON.stringify(req)),corrupt,1),/screening/);assert.deepEqual(store.snapshot('s'),before);assert.throws(()=>store.commit(req,hash(JSON.stringify(req)),b,1,'indexes'));assert.deepEqual(store.snapshot('s'),before);store.commit(req,hash(JSON.stringify(req)),b,1);assert.equal(store.revision(),2);const all=JSON.stringify(store.snapshot('s').erasureSources);assert.doesNotMatch(all,/Your gym is Peak Gym|Peak Gym was my incorrect/);assert.match(all,/My brother goes to Peak Gym|Water is available|Bring water/);assert.ok(store.facts().some(f=>f.value==='Firefox'&&f.state==='active'));}finally{store.close();rmSync(dir,{recursive:true,force:true});}
});
